spring.application.name=WebApplicationSIGEC

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/web_cozinha
?createDatabaseIfNotExist=true
&useSSL=false
&allowPublicKeyRetrieval=true
&serverTimezone=America/Sao_Paulo

spring.datasource.username=root
spring.datasource.password=senac

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Garante que a sessão dura pelo menos 60 minutos
server.servlet.session.timeout=5m

# Impede que o Cookie JSESSIONID mude entre requisições HTTP/HTTPS
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.http-only=true